POST http://localhost:8080/calc
Content-Type: application/json
X-API-Token: token21625747030user1

{
  "value1" : 2,
  "value2" : 2,
  "operation" : "SUM"
}

###

POST http://localhost:8080/calc
Content-Type: application/json
X-API-Token: token21625747030user1

{
  "value1" : 22,
  "value2" : 2.5,
  "operation" : "MULTIPLY"
}

###

POST http://localhost:8080/calc
Content-Type: application/json
X-API-Token: token787225896Test1

{
  "value1" : 22,
  "value2" : 2.5,
  "operation" : "MULTIPLY1"
}

###

GET http://localhost:8080/calc/history
Content-Type: application/json
X-API-Token: token21625747030user1

###

GET http://localhost:8080/calc/history
Content-Type: application/json
#X-API-Token: token21625747030user1

###


